import 'product.dart';
import 'pricing_failure.dart';

class SwapProposal {
  final Product originalProduct;
  final Product alternativeProduct;
  final double? priceDifference; // Null means not fetched. Negative means alternative is cheaper.
  final String healthBenefit; // e.g. "-12g Added Sugar", "Peanut-Free"
  final String? storeLocation; // Null means not fetched.
  final String? storeAddress;
  final double? alternativePrice; // Null means not fetched.
  final String? reasoning; // Reasoning generated by the scoring engine
  final bool isAccepted;
  final bool comparisonAvailable;
  final String? comparisonBasis;
  final double? equivalentAlternativeCost;
  final String? comparisonReason;
  final String? originalQuantityString;
  final String? alternativeQuantityString;
  final String priceDirection; // "savings" | "loss" | "none" — from ComparisonGate
  /// Set when a store-pricing call failed; contains the reason the price is missing.
  final PricingFailure? pricingFailure;

  SwapProposal({
    required this.originalProduct,
    required this.alternativeProduct,
    this.priceDifference,
    required this.healthBenefit,
    this.storeLocation,
    this.storeAddress,
    this.alternativePrice,
    this.reasoning,
    this.isAccepted = false,
    this.comparisonAvailable = true,
    this.comparisonBasis,
    this.equivalentAlternativeCost,
    this.comparisonReason,
    this.originalQuantityString,
    this.alternativeQuantityString,
    this.priceDirection = 'none',
    this.pricingFailure,
  });

  SwapProposal copyWith({
    Product? originalProduct,
    Product? alternativeProduct,
    double? priceDifference,
    String? healthBenefit,
    String? storeLocation,
    String? storeAddress,
    double? alternativePrice,
    String? reasoning,
    bool? isAccepted,
    bool? comparisonAvailable,
    String? comparisonBasis,
    double? equivalentAlternativeCost,
    String? comparisonReason,
    String? originalQuantityString,
    String? alternativeQuantityString,
    String? priceDirection,
    PricingFailure? pricingFailure,
  }) {
    return SwapProposal(
      originalProduct: originalProduct ?? this.originalProduct,
      alternativeProduct: alternativeProduct ?? this.alternativeProduct,
      priceDifference: priceDifference ?? this.priceDifference,
      healthBenefit: healthBenefit ?? this.healthBenefit,
      storeLocation: storeLocation ?? this.storeLocation,
      storeAddress: storeAddress ?? this.storeAddress,
      alternativePrice: alternativePrice ?? this.alternativePrice,
      reasoning: reasoning ?? this.reasoning,
      isAccepted: isAccepted ?? this.isAccepted,
      comparisonAvailable: comparisonAvailable ?? this.comparisonAvailable,
      comparisonBasis: comparisonBasis ?? this.comparisonBasis,
      equivalentAlternativeCost: equivalentAlternativeCost ?? this.equivalentAlternativeCost,
      comparisonReason: comparisonReason ?? this.comparisonReason,
      originalQuantityString: originalQuantityString ?? this.originalQuantityString,
      alternativeQuantityString: alternativeQuantityString ?? this.alternativeQuantityString,
      priceDirection: priceDirection ?? this.priceDirection,
      pricingFailure: pricingFailure ?? this.pricingFailure,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'originalProductId': originalProduct.id,
      'alternativeProductId': alternativeProduct.id,
      'priceDifference': priceDifference,
      'healthBenefit': healthBenefit,
      'storeLocation': storeLocation,
      'storeAddress': storeAddress,
      'alternativePrice': alternativePrice,
      'reasoning': reasoning,
      'isAccepted': isAccepted,
      'comparisonAvailable': comparisonAvailable,
      'comparisonBasis': comparisonBasis,
      'equivalentAlternativeCost': equivalentAlternativeCost,
      'comparisonReason': comparisonReason,
      'originalQuantityString': originalQuantityString,
      'alternativeQuantityString': alternativeQuantityString,
      'priceDirection': priceDirection,
      'pricingFailure': pricingFailure?.name,
    };
  }
}
