import 'product.dart';

class SwapProposal {
  final Product originalProduct;
  final Product alternativeProduct;
  final double priceDifference; // Negative means alternative is cheaper.
  final String healthBenefit; // e.g. "-12g Added Sugar", "Peanut-Free"
  final String storeLocation; // e.g. "Target (1.2 miles away)"
  final String? storeAddress;
  final double alternativePrice;
  final String? reasoning; // Reasoning generated by the scoring engine
  final bool isAccepted;

  SwapProposal({
    required this.originalProduct,
    required this.alternativeProduct,
    required this.priceDifference,
    required this.healthBenefit,
    required this.storeLocation,
    this.storeAddress,
    required this.alternativePrice,
    this.reasoning,
    this.isAccepted = false,
  });

  SwapProposal copyWith({
    Product? originalProduct,
    Product? alternativeProduct,
    double? priceDifference,
    String? healthBenefit,
    String? storeLocation,
    String? storeAddress,
    double? alternativePrice,
    String? reasoning,
    bool? isAccepted,
  }) {
    return SwapProposal(
      originalProduct: originalProduct ?? this.originalProduct,
      alternativeProduct: alternativeProduct ?? this.alternativeProduct,
      priceDifference: priceDifference ?? this.priceDifference,
      healthBenefit: healthBenefit ?? this.healthBenefit,
      storeLocation: storeLocation ?? this.storeLocation,
      storeAddress: storeAddress ?? this.storeAddress,
      alternativePrice: alternativePrice ?? this.alternativePrice,
      reasoning: reasoning ?? this.reasoning,
      isAccepted: isAccepted ?? this.isAccepted,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'originalProductId': originalProduct.id,
      'alternativeProductId': alternativeProduct.id,
      'priceDifference': priceDifference,
      'healthBenefit': healthBenefit,
      'storeLocation': storeLocation,
      'storeAddress': storeAddress,
      'alternativePrice': alternativePrice,
      'reasoning': reasoning,
      'isAccepted': isAccepted,
    };
  }
}
